language: objective-c
osx_image: xcode10
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="JZCalendarWeekView.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="JZCalendarWeekView"
  - IOS_SDK=iphonesimulator
  matrix:
  - DESTINATION="OS=12.0,name=iPhone XS MAX"          SCHEME="$IOS_FRAMEWORK_SCHEME"   SDK="$IOS_SDK"      RUN_TESTS="YES"
  - DESTINATION="OS=11.4.1,name=iPhone X"   SCHEME="$IOS_FRAMEWORK_SCHEME"   SDK="$IOS_SDK"      RUN_TESTS="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"   SDK="$IOS_SDK"      RUN_TESTS="YES"
  - DESTINATION="OS=9.3,name=iPhone 6s"           SCHEME="$IOS_FRAMEWORK_SCHEME"   SDK="$IOS_SDK"      RUN_TESTS="YES"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
